# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Accueil
    url: '/'
    weight: 10
  - name: Formations
    weight: 20
    identifier: cours
  - name: Anglais
    PageRef: cours/english/_index.md
    weight: 10
    parent: cours
  - name: Science
    PageRef: cours/maths/_index.md
    weight: 20
    parent: cours
  - name: Science des donn√©es
    PageRef: cours/data-science/_index.md
    weight: 30
    parent: cours
  - name: Droit tech
    PageRef: cours/data-legal/_index.md
    weight: 40
    parent: cours
  - name: Linguistique
    PageRef: cours/linguistics/_index.md
    weight: 50
    parent: cours
  - name: Blog
    PageRef: post/_index.md
    weight: 30
